In [2]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,Input
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

In [3]:
# Load data
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [4]:
# Normalize the data
X_train = X_train / 255.0
X_test = X_test / 255.0

In [5]:
# Reshape the data from (28, 28) to (784,)
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)


In [6]:
# One-hot encode labels
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [7]:
# Build the model
model = Sequential([
 Input(shape=(784,)),
 Dense(128, activation='relu'),
 Dropout(0.2),
 Dense(10, activation='softmax')
])

In [8]:
# Compile the model
model.compile(optimizer='adam',
 loss='categorical_crossentropy',
 metrics=['accuracy'])

In [9]:
# Train the model
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.5210 - accuracy: 0.8144 - val_loss: 0.4267 - val_accuracy: 0.8482
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3976 - accuracy: 0.8550 - val_loss: 0.3936 - val_accuracy: 0.8575
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3663 - accuracy: 0.8663 - val_loss: 0.3781 - val_accuracy: 0.8645
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3457 - accuracy: 0.8737 - val_loss: 0.3808 - val_accuracy: 0.8618
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3272 - accuracy: 0.8785 - val_loss: 0.3535 - val_accuracy: 0.8715


In [13]:
# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {test_accuracy:.4f}')

313/313 [==============================] - 1s 2ms/step - loss: 0.3535 - accuracy: 0.8715
Test Accuracy: 0.8715


In [10]:
# Predict the labels for the test set
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

313/313 [==============================] - 1s 3ms/step


In [11]:
# Print confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred_classes)
print('Confusion Matrix')
print(conf_matrix)

Confusion Matrix
[[769   0  33  39   1   0 154   0   4   0]
 [  1 972   0  20   3   0   3   0   1   0]
 [  7   0 845  12  82   0  53   0   1   0]
 [ 12  17  14 882  32   0  42   0   1   0]
 [  0   1 142  31 769   0  57   0   0   0]
 [  0   0   0   0   0 958   0  24   1  17]
 [ 96   2 126  35  75   0 660   0   6   0]
 [  0   0   0   0   0  18   0 968   0  14]
 [  4   0  19   6   3   2  12   4 950   0]
 [  0   0   0   0   0   5   1  52   0 942]]


In [12]:
# Print classification report
class_report = classification_report(y_true, y_pred_classes, target_names=[
 'T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot'])
print('Classification Report')
print(class_report)

Classification Report
              precision    recall  f1-score   support

 T-shirt/top       0.87      0.77      0.81      1000
     Trouser       0.98      0.97      0.98      1000
    Pullover       0.72      0.84      0.78      1000
       Dress       0.86      0.88      0.87      1000
        Coat       0.80      0.77      0.78      1000
      Sandal       0.97      0.96      0.97      1000
       Shirt       0.67      0.66      0.67      1000
     Sneaker       0.92      0.97      0.95      1000
         Bag       0.99      0.95      0.97      1000
  Ankle boot       0.97      0.94      0.95      1000

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000

