Task-9:
Implement Build KNN Classification Model

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [7]:
from sklearn.datasets import load_iris
data=load_iris()
import seaborn as sns
data=sns.load_dataset('iris')

In [8]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
data.dropna(axis=0,inplace=True)

In [11]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
x=data.iloc[:,0:4]
y=data.iloc[:,-1]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [19]:
# KNN Classification
#Import library of KNN
from sklearn.neighbors import KNeighborsClassifier
#Store
knn=KNeighborsClassifier(n_neighbors=5)
#fitting
knn.fit(x_train,y_train)
#Prediction
prediction=knn.predict(x_test)
print(prediction)

['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'setosa' 'versicolor' 'versicolor' 'virginica' 'versicolor' 'virginica']


In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusionmatrix=confusion_matrix(y_test,prediction)
print(confusionmatrix)

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
